# Generated by Django 6.0 on 2025-12-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('workspace_type', models.CharField(choices=[('PRIVATE_OFFICE', 'Private Office'), ('MEETING_ROOM', 'Meeting Room'), ('HOT_DESK', 'Hot Desk')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
